### ISSUE TITLE
Pad folders names with 0s to sort them right.

### ISSUE THREAD

**Issue by manishrc** [santumahapatra/100_days_of_dart#1]
![image](https://user-images.githubusercontent.com/324068/84008013-80787d00-a971-11ea-96ed-49fc86e1a46e.png)

`day_1` → `day_001`
...
`day_100` → `day_100`

**Comment by santumahapatra** [comment]
I will fix the issue.

**Comment by santumahapatra** [comment]
Created a Dart Script on day_037 to fix this issue.

I think it took almost over 2 hours. But it was time well spent. I learnt a bit of Dart to fix this - RegExp, Directory and String classes. 

You can find the code here at: https://github.com/santumahapatra/100_days_of_dart/blob/master/day_037/padding_folder_names/pad_folder_names_with_zero.dart

https://github.com/santumahapatra/100_days_of_dart/commit/fdf2d695a51ccee2d300ad814ebf51c324574768
